// Code generated by codegen oapi; DO NOT EDIT.
package testdata

import (
	"time"
)

// User is the generated type for schema User
// User model.
type User struct {
	// Unique user identifier.
	Id string `json:"id"`
	// Optional user age.
	Age *int32 `json:"age,omitzero"`
	// Creation timestamp.
	CreatedAt time.Time `json:"createdAt"`
}

// UserByIDEntry is the generated type for schema UserByID/*
type UserByIDEntry struct {
	// Display name.
	Name string `json:"name"`
	// Email address.
	Email *string `json:"email,omitzero"`
}

// UserByID is the generated type for schema UserByID
// Map from ID to a lightweight user view.
type UserByID map[string]UserByIDEntry

// StringList is the generated type for schema StringList
// List of strings.
type StringList []string
