// Code generated by codegen oapi; DO NOT EDIT.
package testdata

// PriceStep is the generated type for schema PriceStep
// Allowed price steps.
type PriceStep float64

const (
	PriceStep0_5  PriceStep = 0.5
	PriceStep1    PriceStep = 1
	PriceStep1_25 PriceStep = 1.25
)
