// Code generated by codegen oapi; DO NOT EDIT.
package testdata

// OrderCustomer is the generated type for schema Order/customer
// Customer info.
type OrderCustomer struct {
	// Full name.
	Name string `json:"name"`
	// Contact email.
	Email *string `json:"email,omitzero"`
}

// OrderItemsItem is the generated type for schema Order/items/*
// One line item.
type OrderItemsItem struct {
	// Stock keeping unit.
	Sku string `json:"sku"`
	// Quantity.
	Qty int32 `json:"qty"`
}

// Order is the generated type for schema Order
// Order with nested customer, items and metadata map.
type Order struct {
	// Order identifier.
	Id string `json:"id"`
	// Customer info.
	Customer OrderCustomer `json:"customer"`
	// Line items.
	Items []OrderItemsItem `json:"items"`
	// Arbitrary metadata.
	Metadata *map[string]string `json:"metadata,omitzero"`
}
