// Code generated by codegen oapi; DO NOT EDIT.
package testdata

import (
	"time"
)

// StringEnum is the generated type for schema StringEnum
// A string enum.
type StringEnum string

const (
	// The color red
	StringEnumRed StringEnum = "red"
	// The color green
	StringEnumGreen StringEnum = "green"
	// The color blue
	StringEnumBlue StringEnum = "blue"
)

// IntEnum32 is the generated type for schema IntEnum32
// Int32 enum.
type IntEnum32 int32

const (
	IntEnum321 IntEnum32 = 1
	IntEnum322 IntEnum32 = 2
)

// IntEnum64 is the generated type for schema IntEnum64
// Int64 enum.
type IntEnum64 int64

const (
	IntEnum6410000000000 IntEnum64 = 10000000000
	IntEnum6420000000000 IntEnum64 = 20000000000
)

// FloatEnum is the generated type for schema FloatEnum
// Float enum.
type FloatEnum float64

const (
	FloatEnum1_5 FloatEnum = 1.5
	FloatEnum2   FloatEnum = 2
)

// BoolEnum is the generated type for schema BoolEnum
// Bool enum.
type BoolEnum bool

const (
	BoolEnumTrue  BoolEnum = true
	BoolEnumFalse BoolEnum = false
)

// DateType is the generated type for schema DateType
// A timestamp.
type DateType time.Time

// BytesType is the generated type for schema BytesType
// Raw bytes.
type BytesType []byte

// PlainString is the generated type for schema PlainString
// Just a string.
type PlainString string
