// Code generated by codegen oapi; DO NOT EDIT.
package testdata

import (
	"time"
)

// BlobRecord is the generated type for schema BlobRecord
// Demonstrates date-time and byte inside an object.
type BlobRecord struct {
	// Record ID.
	Id string `json:"id"`
	// Raw payload.
	Payload []byte `json:"payload"`
	// Upload time.
	UploadedAt time.Time `json:"uploadedAt"`
	// Optional note.
	Note *string `json:"note,omitzero"`
}
