// Code generated by oapigen; DO NOT EDIT.
package testdata

import (
	"github.com/maketaio/openapi/runtime/fields"
	"github.com/maketaio/openapi/runtime/validation"
)

// Age is the generated type for schema Age
type Age int64

func (o *Age) Validate(path fields.Path) []*validation.Issue {
	if o == nil {
		return nil
	}
	var issues []*validation.Issue
	if *o >= 24 {
		issues = append(issues, validation.NewIntExclMaxIssue(path, 24))
	}
	if *o < 5 {
		issues = append(issues, validation.NewIntMinIssue(path, 5))
	}
	return issues
}

// User is the generated type for schema User
type User struct {
	Id       int64                                      `json:"id"`
	Name     string                                     `json:"name"`
	Age      fields.Optional[Age]                       `json:"age,omitzero"`
	Metadata fields.OptionalNullable[map[string]string] `json:"metadata,omitzero"`
}
